### ISSUE TITLE
Swagger compliant `HX-Request` headers.

### ISSUE THREAD

**Issue by hasansezertasan** [volfpeter/fasthx#5]
Is there a way to make these decorators swagger-compliant?

Edit: The `hx-request` header parameter doesn't show up on the SwaggerUI.

**Comment by hasansezertasan** [comment]
> It can not be done with decorators, because the decorator is applied to / enhances the decorated function, and not the `FastAPI` or `APIRouter` `get`, `post`, etc. methods.

Can't we register annotations to a function wrapped by a decorators?

> What could be done is adding a small utility function that adds the info to the mentioned methods - this may be in the scope of this lib.

Are you talking about modifying the OpenAPI Schema?

> Another option would be subclassing e.g. `APIRouter`, but that's definitely out of scope here.

I couldn't agree more!

**Comment by volfpeter** [comment]
I think I see what you meant now. This could be fixed by adding a `Header` dependency to `get_hx_request()`. I'll get it done soon.

**Comment by hasansezertasan** [comment]
Damn!
